{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: postgres
    {{- range $key, $value := .Values.commonLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app: postgres
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.targetPort }}
    protocol: TCP
    name: postgres
{{- end }}
