services:
  auth-service:
    build: ../../Authentication-Service
    ports:
      - "${AUTH_SERVICE_PORT}:5001"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_SERVICE_URL=${DB_SERVICE_URL}
    networks:
      - auth-net
      - db-net

  logic-service:
    build: ../../Business-Logic-Service
    ports:
      - "${LOGIC_SERVICE_PORT}:5002"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - DB_SERVICE_URL=${DB_SERVICE_URL}
    networks:
      - logic-net
      - db-net

  db-service:
    build: ../../Database-Interaction-Service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${DB_SERVICE_PORT}:5003"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - db-net

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "slotify"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - admin-net
      - db-net

  kong:
    image: kong:3.4
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    volumes:
      - ./infrastructure/kong.yml:/etc/kong/kong.yml
    ports:
      - "${KONG_PROXY_PORT}:8000"
      - "${KONG_ADMIN_PORT}:8001"
    networks:
      - auth-net
      - logic-net

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "${PORTAINER_PORT}:9000"
    networks:
      - admin-net

  prometheus:
    image: prom/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./infrastructure/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - admin-net
      - auth-net
      - logic-net
      - db-net

  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - admin-net

volumes:
  postgres_data:
  portainer_data:
  prometheus_data:
  grafana_data:

networks:
  auth-net:
    driver: bridge
  logic-net:
    driver: bridge
  db-net:
    driver: bridge
  admin-net:
    driver: bridge
