apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: bookmeup
  labels:
    app: adminer
spec:
  type: NodePort  # Accessible from outside cluster
  selector:
    app: adminer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080  # Specific port on host machine
    protocol: TCP
    name: http
