apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: slotify
  labels:
    app: db-service
spec:
  type: ClusterIP
  selector:
    app: db-service
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: http
