apiVersion: v1
kind: Service
metadata:
  name: logic-service
  namespace: bookmeup
  labels:
    app: logic-service
spec:
  type: ClusterIP
  selector:
    app: logic-service
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
    name: http
