apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: bookmeup
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce  # Can be mounted by one node at a time (fine for single-node Minikube)
  resources:
    requests:
      storage: 5Gi  # Request 5GB of storage
  storageClassName: standard  # Minikube's default storage class
